version: "3"
services: 
   auth-db:
    image: postgres:14.7-alpine
    container_name: auth-db
    restart: always
    networks:
      - sales-network
    environment:
      - POSTGRES_DB=auth-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432

   product-db:
    image: postgres:14.7-alpine
    container_name: product-db
    restart: always
    networks:
      - sales-network
    environment:
      - POSTGRES_DB=product-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - 5433:5432

   sales-db:
    image: mongo:latest
    container_name: sales-db
    restart: always
    networks:
      - sales-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
      - 28017:28017

   sales_rabbit:
    image: rabbitmq:3-management
    container_name: sales_rabbit
    hostname: sales_rabbit
    networks:
      - sales-network
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin 
networks:
  sales-network:
    driver: bridge